---
- set_fact:
    openshift_installer_release: "v0.16.1"
    openshift_installer_release_type: "linux"

- name: Setting openshift-installer facts for MacOS
  set_fact:
    openshift_installer_release_type: "darwin"
  when: ansible_os_family == "Darwin"

- set_fact:
    openshift_installer_release_url: "https://github.com/openshift/installer/releases/download/{{ openshift_installer_release }}/openshift-install-{{ openshift_installer_release_type }}-amd64"

- name: get installer
  get_url:
    url: "{{ openshift_installer_release_url }}"
    dest: "{{ playbook_dir }}/openshift-install"
    mode: 0775
